"""
AViGPT: Autonomous Hardware Memory Bus Loop
-------------------------------------------
Orchestrates autonomous hardware inference with KV-caching:
1. Generates tokens using linear O(1) KV-caching (past_key_values).
2. Intercepts <|mem_query|> tokens, fetches ground truth from local SSD in ~1-5ms.
3. Intercepts <|calc|> tokens, calculates exact math in local sandbox.
4. Resumes generation with <|mem_payload|> and produces final synthesis.

Creator & Owner: Avinash Ricky Yadlapalli
"""

import os
import re
import sys
import time
from typing import Tuple, Optional
import torch

from memory_engine import SSDMemoryEngine


def safe_eval_math(expr: str) -> str:
    """Safely evaluates mathematical expressions generated by the model."""
    clean_expr = expr.strip().replace("^", "**").replace("x", "*")
    if not re.match(r'^[0-9+\-*/(). eE]+$', clean_expr):
        return "Invalid math expression"
    try:
        val = eval(clean_expr, {"__builtins__": None}, {})
        if isinstance(val, float):
            return f"{val:.6g}"
        return str(val)
    except Exception as e:
        return f"Calculation error: {e}"


class AutonomousHardwareBus:
    def __init__(self, model, tokenizer, device="cuda", db_path: Optional[str] = None):
        self.model = model
        self.tokenizer = tokenizer
        self.device = device
        self.memory = SSDMemoryEngine(db_path) if db_path else SSDMemoryEngine()
        self.memory.seed_initial_knowledge()

        if device == "cpu" and hasattr(torch, "set_num_threads"):
            # Maximize available CPU execution threads
            max_threads = os.cpu_count() or 4
            torch.set_num_threads(max_threads)

    def generate_autonomous_response(
        self,
        instruction: str,
        max_total_tokens: int = 180,
        temperature: float = 0.2,
        top_p: float = 0.9,
    ) -> Tuple[str, dict]:
        """
        Runs the closed-loop autonomous hardware bus with KV-cache optimization:
        Model -> [Special Tokens Intercepted] -> SSD / Calc -> Final Output.
        """
        metrics = {
            "ssd_memory_hits": 0,
            "calc_hits": 0,
            "ssd_latency_ms": 0.0,
            "total_latency_s": 0.0,
            "tokens_generated": 0,
        }

        t_total_start = time.time()
        prompt_text = (
            "Below is an instruction that describes a task. "
            "Write a response that appropriately completes the request.\n\n"
            f"### Instruction:\n{instruction}\n\n### Response:\n"
        )

        encoded = self.tokenizer(prompt_text, return_tensors="pt")
        input_ids = encoded["input_ids"].to(self.device)
        if input_ids.dim() == 1:
            input_ids = input_ids.unsqueeze(0)

        eos_id = self.tokenizer.eos_token_id

        output_tokens = []
        past_key_values = None
        model_inputs = input_ids
        has_injected_mem = False
        has_injected_calc = False

        for step in range(max_total_tokens):
            with torch.no_grad():
                out = self.model(model_inputs, past_key_values=past_key_values, use_cache=True)
                past_key_values = out.past_key_values
                logits = out.logits[:, -1, :].clone()

                # 1. Standard repetition penalty on recent tokens
                if output_tokens:
                    for prev_token_id in set(output_tokens[-60:]):
                        if logits[0, prev_token_id] < 0:
                            logits[0, prev_token_id] *= 1.2
                        else:
                            logits[0, prev_token_id] /= 1.2

                # 2. Hard N-gram block: guarantees no 3-token phrase repeats in the output
                ngram_size = 3
                if len(output_tokens) >= ngram_size - 1:
                    prefix = tuple(output_tokens[-(ngram_size - 1):])
                    for i in range(len(output_tokens) - ngram_size + 1):
                        if tuple(output_tokens[i : i + ngram_size - 1]) == prefix:
                            logits[0, output_tokens[i + ngram_size - 1]] = -float('inf')

                if temperature > 0.05:
                    probs = torch.softmax(logits / temperature, dim=-1)
                    next_token = torch.multinomial(probs, num_samples=1)
                else:
                    next_token = torch.argmax(logits, dim=-1, keepdim=True)

            token_id = next_token.item()
            if token_id == eos_id:
                break

            output_tokens.append(token_id)
            metrics["tokens_generated"] += 1
            model_inputs = next_token

            # Repetition / Loop Guard: if last 4 tokens repeated consecutively
            if len(output_tokens) >= 8:
                if output_tokens[-4:] == output_tokens[-8:-4]:
                    break

            current_text = self.tokenizer.decode(output_tokens)

            # Check for early exit once synthesis completes
            if "<|synthesize|>" in current_text:
                synth_part = current_text.split("<|synthesize|>")[-1]
                if "<|endoftext|>" in synth_part or "\n\n" in synth_part.strip():
                    break
                # If synthesized sentence ends with punctuation and has adequate content
                if len(synth_part.strip()) > 15 and synth_part.rstrip().endswith((".", "!", "?")):
                    break

            # 1. Hardware Bus: SSD Memory Intercept
            mem_match = re.search(r'<\|mem_query\|>(.*?)<\|mem_query_end\|>', current_text)
            if mem_match and not has_injected_mem:
                query_str = mem_match.group(1).strip()
                t0 = time.perf_counter()
                payload = self.memory.query(query_str)
                lat_ms = (time.perf_counter() - t0) * 1000.0

                metrics["ssd_memory_hits"] += 1
                metrics["ssd_latency_ms"] += lat_ms

                if not payload:
                    payload = "Information not found in local SSD memory."

                injected_text = f"\n<|mem_payload|> {payload} <|mem_payload_end|>\n"
                injected_enc = self.tokenizer(injected_text, add_special_tokens=False, return_tensors="pt")
                injected_ids = injected_enc["input_ids"].to(self.device)
                if injected_ids.dim() == 1:
                    injected_ids = injected_ids.unsqueeze(0)

                output_tokens.extend(injected_ids[0].tolist())
                model_inputs = injected_ids
                has_injected_mem = True

            # 2. Hardware Bus: Calculation Intercept
            calc_match = re.search(r'<\|calc\|>(.*?)<\|calc_end\|>', current_text)
            if calc_match and not has_injected_calc:
                expr = calc_match.group(1).strip()
                res = safe_eval_math(expr)
                metrics["calc_hits"] += 1

                injected_text = f"\n<|calc_res|> {res} <|calc_res_end|>\n"
                injected_enc = self.tokenizer(injected_text, add_special_tokens=False, return_tensors="pt")
                injected_ids = injected_enc["input_ids"].to(self.device)
                if injected_ids.dim() == 1:
                    injected_ids = injected_ids.unsqueeze(0)

                output_tokens.extend(injected_ids[0].tolist())
                model_inputs = injected_ids
                has_injected_calc = True

        full_generated_text = self.tokenizer.decode(output_tokens)
        metrics["total_latency_s"] = time.time() - t_total_start

        return full_generated_text, metrics
